@baseUrl = http://localhost:5128
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwYjY3OS1iOTY5LTdhODUtYWE2NC1hYzY5NjQzYTdmMjkiLCJlbWFpbCI6ImZlaGludG9sdXNhbXVlbEBnbWFpbC5jb20iLCJleHAiOjE3ODk4MjgwMzYsImlzcyI6IlRyZW5keVNpemVBcGkiLCJhdWQiOiJUcmVuZHlTaXplQ2xpZW50In0.5JRRkOqt2slwZS0MoDX6XmOzWWkd8ha26viX8Yqsh4s
### Signup
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "fehintolusamuel@gmail.com",
  "password": "Password123!",
  "phoneNumber": "+2348012345678"
}

### Confirm Email
POST {{baseUrl}}/api/auth/confirm-email
Content-Type: application/json

{
  "userId": "01a0b679-b969-7a85-aa64-ac69643a7f29",
  "token": "CfDJ8CeWQk9+vF9ArMrMNnNA2lI2Xsai6nl30I71iogQTifxdlOxrZvjmRdhMJVtktSiVUI92MhHnKeVzxBYE6VXaEoT3QxpU6PE/a/Xv5tUhupxVu7kmOWpbAJ2ZZjdFvNAUHFo6rZnZ3KtAFInysxFVynarVzjzNHwYHfZ0/UHBgO3xkERw+/GnunHNu5BBWCbYP4c9BBUVZHuWx7E3v2FYb7XnWWSdw3BaG6v473EmQoJ3nBsu1BFWOA33InRLt5sLg=="
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "fehintolusamuel@gmail.com",
  "password": "Password123!"
}


### Get Profile
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}

### Update Profile
PUT {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "whatsappNumber": "+2348012345678"
}

### Test Endpoint
GET {{baseUrl}}/api/auth/test

### Test Create Customer Endpoint
POST  {{baseUrl}}/api/customers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Test2",
  "lastName": "User2",
  "phoneNumber": "+2348012345670",
  "gender": 0
}

### Test Get All Customers Endpoint
GET  {{baseUrl}}/api/customers
Authorization: Bearer {{token}}


### Generate Measurement Link
POST {{baseUrl}}/api/measurements/generate-link
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "customerId": 1,
  "orderReference": "ORD-001"
}

### WhatsApp Redirect
GET {{baseUrl}}/api/public/v/fehintolusamuel@gmail.com